/**
 * Genererer copy-paste `canvas:error` payloads til
 * `docs/mcp-bridge-error-payloads.generated.md` direkte fra
 * fejlkodespecifikationen i `widgetdcContracts.ts`.
 *
 * Reglen: docs må **aldrig** indeholde håndskrevne payloads — de skal
 * produceres ved at køre de samme funktioner (`validateIncomingBridgeMessage`,
 * `buildOriginRejection`, `buildCanvasErrorMessage`) som embed-bridgen
 * bruger i runtime. Drift mellem docs og kode fanges af
 * `bridgeErrorDocs.test.ts`.
 */
import {
  type BridgeMessage,
  type BridgeRejection,
  buildCanvasErrorMessage,
  buildOriginRejection,
  isAllowedOrigin,
  validateIncomingBridgeMessage,
} from "./widgetdcContracts";

export const DOCS_CANVAS_ID = "aurora-canvas-abc123";
export const DOCS_BASE_TS = 1_717_584_000_000;

interface OriginCase {
  title: string;
  receivedOrigin: string | null;
  allowedOrigins: readonly string[];
}

interface SchemaCase {
  title: string;
  raw: unknown;
}

const ORIGIN_CASES: OriginCase[] = [
  {
    title: "Afsender-origin ikke på allow-list",
    receivedOrigin: "https://attacker.example",
    allowedOrigins: ["https://host.example"],
  },
  {
    title: "Opaque origin (`null` — fx `file://` eller sandboxed iframe)",
    receivedOrigin: null,
    allowedOrigins: ["https://host.example"],
  },
  {
    title: "Forkert port",
    receivedOrigin: "https://host.example:8080",
    allowedOrigins: ["https://host.example"],
  },
];

const SCHEMA_CASES: SchemaCase[] = [
  {
    title: "Forkert contract-version",
    raw: {
      v: 1,
      contract: "widgetdc.bridge.v2",
      canvas_id: DOCS_CANVAS_ID,
      type: "host:hello",
      ts: DOCS_BASE_TS,
    },
  },
  {
    title: "Manglende felt (`canvas_id`)",
    raw: {
      v: 1,
      contract: "widgetdc.bridge.v1",
      type: "host:hello",
      ts: DOCS_BASE_TS,
    },
  },
  {
    title: "Ukendt `type`",
    raw: {
      v: 1,
      contract: "widgetdc.bridge.v1",
      canvas_id: DOCS_CANVAS_ID,
      type: "rogue:type",
      ts: DOCS_BASE_TS,
    },
  },
  {
    title: "Primitiv payload (`null`)",
    raw: null,
  },
  {
    title: "canvas_id matcher ikke embed'ets ID",
    raw: {
      v: 1,
      contract: "widgetdc.bridge.v1",
      canvas_id: "aurora-canvas-ROGUE",
      type: "host:hello",
      ts: DOCS_BASE_TS,
    },
  },
];

function rejectionForOrigin(c: OriginCase): BridgeRejection | null {
  if (isAllowedOrigin(c.receivedOrigin, c.allowedOrigins)) return null;
  return buildOriginRejection(c.receivedOrigin, c.allowedOrigins);
}

function rejectionForSchema(c: SchemaCase): BridgeRejection | null {
  const result = validateIncomingBridgeMessage(c.raw, DOCS_CANVAS_ID);
  return result.ok ? null : result.rejection;
}

/**
 * Kanonisk JSON-serialisering: rekursiv key-sortering (alfabetisk),
 * 2-space indent, LF line endings. Sikrer at den genererede markdown
 * er bit-identisk på tværs af miljøer (Node-version, OS, locale) og
 * uafhængig af insertion-order i koden — så et felt-omarrangement i
 * `buildCanvasErrorMessage` ikke fører til docs-diff.
 */
function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === "object") {
    const src = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(src).sort()) {
      out[key] = canonicalize(src[key]);
    }
    return out;
  }
  return value;
}

export function canonicalJson(value: unknown): string {
  return JSON.stringify(canonicalize(value), null, 2).replace(/\r\n/g, "\n");
}

function renderEnvelope(msg: BridgeMessage): string {
  return "```json\n" + canonicalJson(msg) + "\n```";
}

function renderRawInput(raw: unknown): string {
  return "```json\n" + canonicalJson(raw) + "\n```";
}

/**
 * Genererer det fulde markdown-dokument deterministisk. Skal være pure —
 * ingen tilfældige IDs eller `Date.now()` — så drift-testen er stabil.
 */
export function generateBridgeErrorDocs(): string {
  const lines: string[] = [];
  lines.push("<!-- AUTO-GENERATED by scripts/generate-bridge-error-docs.ts — DO NOT EDIT. -->");
  lines.push("<!-- Kør `bun run docs:bridge-errors` for at regenerere. -->");
  lines.push("");
  lines.push("# `canvas:error` payloads (genereret)");
  lines.push("");
  lines.push(
    "Disse payloads er produceret direkte fra `validateIncomingBridgeMessage`,",
    "`buildOriginRejection` og `buildCanvasErrorMessage` i `widgetdcContracts.ts`.",
    "Hvis fejlkode-specifikationen ændrer sig, regenereres filen — så docs og runtime",
    "kan ikke komme out of sync.",
  );
  lines.push("");
  lines.push(`Konstante værdier brugt i eksemplerne:`);
  lines.push("");
  lines.push(`- \`canvas_id\` = \`"${DOCS_CANVAS_ID}"\``);
  lines.push(`- \`ts\` baseline = \`${DOCS_BASE_TS}\` (inkrementeres per case)`);
  lines.push("");

  let ts = DOCS_BASE_TS;

  lines.push("## Origin-afvisninger");
  lines.push("");
  for (const c of ORIGIN_CASES) {
    const rejection = rejectionForOrigin(c);
    if (!rejection) {
      throw new Error(`Origin-case "${c.title}" forventede afvisning men fik OK`);
    }
    const envelope = buildCanvasErrorMessage(DOCS_CANVAS_ID, rejection, ++ts);
    lines.push(`### ${c.title}`);
    lines.push("");
    lines.push(
      `Input: \`received_origin = ${
        c.receivedOrigin === null ? "null" : `"${c.receivedOrigin}"`
      }\`, \`allowed_origins = ${JSON.stringify(c.allowedOrigins)}\``,
    );
    lines.push("");
    lines.push(renderEnvelope(envelope));
    lines.push("");
  }

  lines.push("## Schema- / kontrakt-afvisninger");
  lines.push("");
  for (const c of SCHEMA_CASES) {
    const rejection = rejectionForSchema(c);
    if (!rejection) {
      throw new Error(`Schema-case "${c.title}" forventede afvisning men fik OK`);
    }
    const envelope = buildCanvasErrorMessage(DOCS_CANVAS_ID, rejection, ++ts);
    lines.push(`### ${c.title} (\`${rejection.code}\`)`);
    lines.push("");
    lines.push("Indkommende rå payload:");
    lines.push("");
    lines.push(renderRawInput(c.raw));
    lines.push("");
    lines.push("Embed sender til host:");
    lines.push("");
    lines.push(renderEnvelope(envelope));
    lines.push("");
  }

  return lines.join("\n").replace(/\n+$/g, "") + "\n";
}

export const GENERATED_DOC_PATH = "docs/mcp-bridge-error-payloads.generated.md";
