/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorylineRouteImport } from './routes/storyline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MondayReviewRouteImport } from './routes/monday-review'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as DeliverableRouteImport } from './routes/deliverable'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as AuditFactoryRouteImport } from './routes/audit-factory'
import { Route as AdoptionRouteImport } from './routes/adoption'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GemsIndexRouteImport } from './routes/gems.index'
import { Route as VisualGraphRouteImport } from './routes/visual.graph'
import { Route as GemsGemIdRouteImport } from './routes/gems.$gemId'
import { Route as DebugLogsRouteImport } from './routes/debug.logs'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'
import { Route as ApiStorylineRouteImport } from './routes/api/storyline'
import { Route as ApiReleaseRouteImport } from './routes/api/release'
import { Route as ApiPatternsRouteImport } from './routes/api/patterns'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiMondayReviewRouteImport } from './routes/api/monday-review'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiEngagementsRouteImport } from './routes/api/engagements'
import { Route as ApiDeepResearchRouteImport } from './routes/api/deep-research'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAudioOverviewRouteImport } from './routes/api/audio-overview'
import { Route as EmbedCanvasCanvasIdRouteImport } from './routes/embed.canvas.$canvasId'
import { Route as ApiObservabilitySummaryRouteImport } from './routes/api/observability.summary'
import { Route as ApiNewsRefreshRouteImport } from './routes/api/news.refresh'
import { Route as ApiGraphQueryRouteImport } from './routes/api/graph.query'
import { Route as ApiDeliverableGenerateRouteImport } from './routes/api/deliverable.generate'
import { Route as ApiDeliverableExportRouteImport } from './routes/api/deliverable.export'
import { Route as ApiConsultingAssembleRouteImport } from './routes/api/consulting.assemble'
import { Route as ApiApprovalsOrchestratorRouteImport } from './routes/api/approvals.orchestrator'
import { Route as ApiApprovalsBackendRouteImport } from './routes/api/approvals.backend'
import { Route as ApiAdoptionMetricsRouteImport } from './routes/api/adoption.metrics'
import { Route as ApiMrpCanvasResolveRouteImport } from './routes/api/mrp.canvas.resolve'
import { Route as ApiEngagementsIdSourcesRouteImport } from './routes/api/engagements.$id.sources'
import { Route as ApiEngagementsIdPatternsRouteImport } from './routes/api/engagements.$id.patterns'
import { Route as ApiEngagementsIdDeliverableRouteImport } from './routes/api/engagements.$id.deliverable'

const StorylineRoute = StorylineRouteImport.update({
  id: '/storyline',
  path: '/storyline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MondayReviewRoute = MondayReviewRouteImport.update({
  id: '/monday-review',
  path: '/monday-review',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverableRoute = DeliverableRouteImport.update({
  id: '/deliverable',
  path: '/deliverable',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditFactoryRoute = AuditFactoryRouteImport.update({
  id: '/audit-factory',
  path: '/audit-factory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionRoute = AdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsIndexRoute = GemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GemsRoute,
} as any)
const VisualGraphRoute = VisualGraphRouteImport.update({
  id: '/visual/graph',
  path: '/visual/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsGemIdRoute = GemsGemIdRouteImport.update({
  id: '/$gemId',
  path: '/$gemId',
  getParentRoute: () => GemsRoute,
} as any)
const DebugLogsRoute = DebugLogsRouteImport.update({
  id: '/debug/logs',
  path: '/debug/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorylineRoute = ApiStorylineRouteImport.update({
  id: '/api/storyline',
  path: '/api/storyline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleaseRoute = ApiReleaseRouteImport.update({
  id: '/api/release',
  path: '/api/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatternsRoute = ApiPatternsRouteImport.update({
  id: '/api/patterns',
  path: '/api/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMondayReviewRoute = ApiMondayReviewRouteImport.update({
  id: '/api/monday-review',
  path: '/api/monday-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngagementsRoute = ApiEngagementsRouteImport.update({
  id: '/api/engagements',
  path: '/api/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeepResearchRoute = ApiDeepResearchRouteImport.update({
  id: '/api/deep-research',
  path: '/api/deep-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioOverviewRoute = ApiAudioOverviewRouteImport.update({
  id: '/api/audio-overview',
  path: '/api/audio-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCanvasCanvasIdRoute = EmbedCanvasCanvasIdRouteImport.update({
  id: '/embed/canvas/$canvasId',
  path: '/embed/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilitySummaryRoute = ApiObservabilitySummaryRouteImport.update({
  id: '/api/observability/summary',
  path: '/api/observability/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRefreshRoute = ApiNewsRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiGraphQueryRoute = ApiGraphQueryRouteImport.update({
  id: '/api/graph/query',
  path: '/api/graph/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliverableGenerateRoute = ApiDeliverableGenerateRouteImport.update({
  id: '/api/deliverable/generate',
  path: '/api/deliverable/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliverableExportRoute = ApiDeliverableExportRouteImport.update({
  id: '/api/deliverable/export',
  path: '/api/deliverable/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultingAssembleRoute = ApiConsultingAssembleRouteImport.update({
  id: '/api/consulting/assemble',
  path: '/api/consulting/assemble',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApprovalsOrchestratorRoute =
  ApiApprovalsOrchestratorRouteImport.update({
    id: '/api/approvals/orchestrator',
    path: '/api/approvals/orchestrator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApprovalsBackendRoute = ApiApprovalsBackendRouteImport.update({
  id: '/api/approvals/backend',
  path: '/api/approvals/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdoptionMetricsRoute = ApiAdoptionMetricsRouteImport.update({
  id: '/api/adoption/metrics',
  path: '/api/adoption/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMrpCanvasResolveRoute = ApiMrpCanvasResolveRouteImport.update({
  id: '/api/mrp/canvas/resolve',
  path: '/api/mrp/canvas/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngagementsIdSourcesRoute = ApiEngagementsIdSourcesRouteImport.update({
  id: '/$id/sources',
  path: '/$id/sources',
  getParentRoute: () => ApiEngagementsRoute,
} as any)
const ApiEngagementsIdPatternsRoute =
  ApiEngagementsIdPatternsRouteImport.update({
    id: '/$id/patterns',
    path: '/$id/patterns',
    getParentRoute: () => ApiEngagementsRoute,
  } as any)
const ApiEngagementsIdDeliverableRoute =
  ApiEngagementsIdDeliverableRouteImport.update({
    id: '/$id/deliverable',
    path: '/$id/deliverable',
    getParentRoute: () => ApiEngagementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/audit-factory': typeof AuditFactoryRoute
  '/capabilities': typeof CapabilitiesRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/deliverable': typeof DeliverableRoute
  '/engagements': typeof EngagementsRoute
  '/gems': typeof GemsRouteWithChildren
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/monday-review': typeof MondayReviewRoute
  '/news': typeof NewsRoute
  '/observability': typeof ObservabilityRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
  '/storyline': typeof StorylineRoute
  '/api/audio-overview': typeof ApiAudioOverviewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cost': typeof ApiCostRoute
  '/api/deep-research': typeof ApiDeepResearchRoute
  '/api/engagements': typeof ApiEngagementsRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/api/monday-review': typeof ApiMondayReviewRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/patterns': typeof ApiPatternsRoute
  '/api/release': typeof ApiReleaseRoute
  '/api/storyline': typeof ApiStorylineRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/gems/': typeof GemsIndexRoute
  '/api/adoption/metrics': typeof ApiAdoptionMetricsRoute
  '/api/approvals/backend': typeof ApiApprovalsBackendRoute
  '/api/approvals/orchestrator': typeof ApiApprovalsOrchestratorRoute
  '/api/consulting/assemble': typeof ApiConsultingAssembleRoute
  '/api/deliverable/export': typeof ApiDeliverableExportRoute
  '/api/deliverable/generate': typeof ApiDeliverableGenerateRoute
  '/api/graph/query': typeof ApiGraphQueryRoute
  '/api/news/refresh': typeof ApiNewsRefreshRoute
  '/api/observability/summary': typeof ApiObservabilitySummaryRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/engagements/$id/deliverable': typeof ApiEngagementsIdDeliverableRoute
  '/api/engagements/$id/patterns': typeof ApiEngagementsIdPatternsRoute
  '/api/engagements/$id/sources': typeof ApiEngagementsIdSourcesRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/audit-factory': typeof AuditFactoryRoute
  '/capabilities': typeof CapabilitiesRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/deliverable': typeof DeliverableRoute
  '/engagements': typeof EngagementsRoute
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/monday-review': typeof MondayReviewRoute
  '/news': typeof NewsRoute
  '/observability': typeof ObservabilityRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
  '/storyline': typeof StorylineRoute
  '/api/audio-overview': typeof ApiAudioOverviewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cost': typeof ApiCostRoute
  '/api/deep-research': typeof ApiDeepResearchRoute
  '/api/engagements': typeof ApiEngagementsRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/api/monday-review': typeof ApiMondayReviewRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/patterns': typeof ApiPatternsRoute
  '/api/release': typeof ApiReleaseRoute
  '/api/storyline': typeof ApiStorylineRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/gems': typeof GemsIndexRoute
  '/api/adoption/metrics': typeof ApiAdoptionMetricsRoute
  '/api/approvals/backend': typeof ApiApprovalsBackendRoute
  '/api/approvals/orchestrator': typeof ApiApprovalsOrchestratorRoute
  '/api/consulting/assemble': typeof ApiConsultingAssembleRoute
  '/api/deliverable/export': typeof ApiDeliverableExportRoute
  '/api/deliverable/generate': typeof ApiDeliverableGenerateRoute
  '/api/graph/query': typeof ApiGraphQueryRoute
  '/api/news/refresh': typeof ApiNewsRefreshRoute
  '/api/observability/summary': typeof ApiObservabilitySummaryRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/engagements/$id/deliverable': typeof ApiEngagementsIdDeliverableRoute
  '/api/engagements/$id/patterns': typeof ApiEngagementsIdPatternsRoute
  '/api/engagements/$id/sources': typeof ApiEngagementsIdSourcesRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/audit-factory': typeof AuditFactoryRoute
  '/capabilities': typeof CapabilitiesRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/deliverable': typeof DeliverableRoute
  '/engagements': typeof EngagementsRoute
  '/gems': typeof GemsRouteWithChildren
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/monday-review': typeof MondayReviewRoute
  '/news': typeof NewsRoute
  '/observability': typeof ObservabilityRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
  '/storyline': typeof StorylineRoute
  '/api/audio-overview': typeof ApiAudioOverviewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cost': typeof ApiCostRoute
  '/api/deep-research': typeof ApiDeepResearchRoute
  '/api/engagements': typeof ApiEngagementsRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/api/monday-review': typeof ApiMondayReviewRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/patterns': typeof ApiPatternsRoute
  '/api/release': typeof ApiReleaseRoute
  '/api/storyline': typeof ApiStorylineRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/gems/': typeof GemsIndexRoute
  '/api/adoption/metrics': typeof ApiAdoptionMetricsRoute
  '/api/approvals/backend': typeof ApiApprovalsBackendRoute
  '/api/approvals/orchestrator': typeof ApiApprovalsOrchestratorRoute
  '/api/consulting/assemble': typeof ApiConsultingAssembleRoute
  '/api/deliverable/export': typeof ApiDeliverableExportRoute
  '/api/deliverable/generate': typeof ApiDeliverableGenerateRoute
  '/api/graph/query': typeof ApiGraphQueryRoute
  '/api/news/refresh': typeof ApiNewsRefreshRoute
  '/api/observability/summary': typeof ApiObservabilitySummaryRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/engagements/$id/deliverable': typeof ApiEngagementsIdDeliverableRoute
  '/api/engagements/$id/patterns': typeof ApiEngagementsIdPatternsRoute
  '/api/engagements/$id/sources': typeof ApiEngagementsIdSourcesRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adoption'
    | '/audit-factory'
    | '/capabilities'
    | '/consulting'
    | '/dashboard'
    | '/deliverable'
    | '/engagements'
    | '/gems'
    | '/graph'
    | '/health'
    | '/monday-review'
    | '/news'
    | '/observability'
    | '/patterns'
    | '/settings'
    | '/storyline'
    | '/api/audio-overview'
    | '/api/chat'
    | '/api/cost'
    | '/api/deep-research'
    | '/api/engagements'
    | '/api/ingest'
    | '/api/monday-review'
    | '/api/news'
    | '/api/patterns'
    | '/api/release'
    | '/api/storyline'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/gems/'
    | '/api/adoption/metrics'
    | '/api/approvals/backend'
    | '/api/approvals/orchestrator'
    | '/api/consulting/assemble'
    | '/api/deliverable/export'
    | '/api/deliverable/generate'
    | '/api/graph/query'
    | '/api/news/refresh'
    | '/api/observability/summary'
    | '/embed/canvas/$canvasId'
    | '/api/engagements/$id/deliverable'
    | '/api/engagements/$id/patterns'
    | '/api/engagements/$id/sources'
    | '/api/mrp/canvas/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adoption'
    | '/audit-factory'
    | '/capabilities'
    | '/consulting'
    | '/dashboard'
    | '/deliverable'
    | '/engagements'
    | '/graph'
    | '/health'
    | '/monday-review'
    | '/news'
    | '/observability'
    | '/patterns'
    | '/settings'
    | '/storyline'
    | '/api/audio-overview'
    | '/api/chat'
    | '/api/cost'
    | '/api/deep-research'
    | '/api/engagements'
    | '/api/ingest'
    | '/api/monday-review'
    | '/api/news'
    | '/api/patterns'
    | '/api/release'
    | '/api/storyline'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/gems'
    | '/api/adoption/metrics'
    | '/api/approvals/backend'
    | '/api/approvals/orchestrator'
    | '/api/consulting/assemble'
    | '/api/deliverable/export'
    | '/api/deliverable/generate'
    | '/api/graph/query'
    | '/api/news/refresh'
    | '/api/observability/summary'
    | '/embed/canvas/$canvasId'
    | '/api/engagements/$id/deliverable'
    | '/api/engagements/$id/patterns'
    | '/api/engagements/$id/sources'
    | '/api/mrp/canvas/resolve'
  id:
    | '__root__'
    | '/'
    | '/adoption'
    | '/audit-factory'
    | '/capabilities'
    | '/consulting'
    | '/dashboard'
    | '/deliverable'
    | '/engagements'
    | '/gems'
    | '/graph'
    | '/health'
    | '/monday-review'
    | '/news'
    | '/observability'
    | '/patterns'
    | '/settings'
    | '/storyline'
    | '/api/audio-overview'
    | '/api/chat'
    | '/api/cost'
    | '/api/deep-research'
    | '/api/engagements'
    | '/api/ingest'
    | '/api/monday-review'
    | '/api/news'
    | '/api/patterns'
    | '/api/release'
    | '/api/storyline'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/gems/'
    | '/api/adoption/metrics'
    | '/api/approvals/backend'
    | '/api/approvals/orchestrator'
    | '/api/consulting/assemble'
    | '/api/deliverable/export'
    | '/api/deliverable/generate'
    | '/api/graph/query'
    | '/api/news/refresh'
    | '/api/observability/summary'
    | '/embed/canvas/$canvasId'
    | '/api/engagements/$id/deliverable'
    | '/api/engagements/$id/patterns'
    | '/api/engagements/$id/sources'
    | '/api/mrp/canvas/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptionRoute: typeof AdoptionRoute
  AuditFactoryRoute: typeof AuditFactoryRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  ConsultingRoute: typeof ConsultingRoute
  DashboardRoute: typeof DashboardRoute
  DeliverableRoute: typeof DeliverableRoute
  EngagementsRoute: typeof EngagementsRoute
  GemsRoute: typeof GemsRouteWithChildren
  GraphRoute: typeof GraphRoute
  HealthRoute: typeof HealthRoute
  MondayReviewRoute: typeof MondayReviewRoute
  NewsRoute: typeof NewsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  PatternsRoute: typeof PatternsRoute
  SettingsRoute: typeof SettingsRoute
  StorylineRoute: typeof StorylineRoute
  ApiAudioOverviewRoute: typeof ApiAudioOverviewRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCostRoute: typeof ApiCostRoute
  ApiDeepResearchRoute: typeof ApiDeepResearchRoute
  ApiEngagementsRoute: typeof ApiEngagementsRouteWithChildren
  ApiIngestRoute: typeof ApiIngestRoute
  ApiMondayReviewRoute: typeof ApiMondayReviewRoute
  ApiNewsRoute: typeof ApiNewsRouteWithChildren
  ApiPatternsRoute: typeof ApiPatternsRoute
  ApiReleaseRoute: typeof ApiReleaseRoute
  ApiStorylineRoute: typeof ApiStorylineRoute
  CThreadIdRoute: typeof CThreadIdRoute
  DebugLogsRoute: typeof DebugLogsRoute
  VisualGraphRoute: typeof VisualGraphRoute
  ApiAdoptionMetricsRoute: typeof ApiAdoptionMetricsRoute
  ApiApprovalsBackendRoute: typeof ApiApprovalsBackendRoute
  ApiApprovalsOrchestratorRoute: typeof ApiApprovalsOrchestratorRoute
  ApiConsultingAssembleRoute: typeof ApiConsultingAssembleRoute
  ApiDeliverableExportRoute: typeof ApiDeliverableExportRoute
  ApiDeliverableGenerateRoute: typeof ApiDeliverableGenerateRoute
  ApiGraphQueryRoute: typeof ApiGraphQueryRoute
  ApiObservabilitySummaryRoute: typeof ApiObservabilitySummaryRoute
  EmbedCanvasCanvasIdRoute: typeof EmbedCanvasCanvasIdRoute
  ApiMrpCanvasResolveRoute: typeof ApiMrpCanvasResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storyline': {
      id: '/storyline'
      path: '/storyline'
      fullPath: '/storyline'
      preLoaderRoute: typeof StorylineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monday-review': {
      id: '/monday-review'
      path: '/monday-review'
      fullPath: '/monday-review'
      preLoaderRoute: typeof MondayReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverable': {
      id: '/deliverable'
      path: '/deliverable'
      fullPath: '/deliverable'
      preLoaderRoute: typeof DeliverableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-factory': {
      id: '/audit-factory'
      path: '/audit-factory'
      fullPath: '/audit-factory'
      preLoaderRoute: typeof AuditFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/': {
      id: '/gems/'
      path: '/'
      fullPath: '/gems/'
      preLoaderRoute: typeof GemsIndexRouteImport
      parentRoute: typeof GemsRoute
    }
    '/visual/graph': {
      id: '/visual/graph'
      path: '/visual/graph'
      fullPath: '/visual/graph'
      preLoaderRoute: typeof VisualGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/$gemId': {
      id: '/gems/$gemId'
      path: '/$gemId'
      fullPath: '/gems/$gemId'
      preLoaderRoute: typeof GemsGemIdRouteImport
      parentRoute: typeof GemsRoute
    }
    '/debug/logs': {
      id: '/debug/logs'
      path: '/debug/logs'
      fullPath: '/debug/logs'
      preLoaderRoute: typeof DebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storyline': {
      id: '/api/storyline'
      path: '/api/storyline'
      fullPath: '/api/storyline'
      preLoaderRoute: typeof ApiStorylineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/release': {
      id: '/api/release'
      path: '/api/release'
      fullPath: '/api/release'
      preLoaderRoute: typeof ApiReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns': {
      id: '/api/patterns'
      path: '/api/patterns'
      fullPath: '/api/patterns'
      preLoaderRoute: typeof ApiPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monday-review': {
      id: '/api/monday-review'
      path: '/api/monday-review'
      fullPath: '/api/monday-review'
      preLoaderRoute: typeof ApiMondayReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engagements': {
      id: '/api/engagements'
      path: '/api/engagements'
      fullPath: '/api/engagements'
      preLoaderRoute: typeof ApiEngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deep-research': {
      id: '/api/deep-research'
      path: '/api/deep-research'
      fullPath: '/api/deep-research'
      preLoaderRoute: typeof ApiDeepResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio-overview': {
      id: '/api/audio-overview'
      path: '/api/audio-overview'
      fullPath: '/api/audio-overview'
      preLoaderRoute: typeof ApiAudioOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/canvas/$canvasId': {
      id: '/embed/canvas/$canvasId'
      path: '/embed/canvas/$canvasId'
      fullPath: '/embed/canvas/$canvasId'
      preLoaderRoute: typeof EmbedCanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/summary': {
      id: '/api/observability/summary'
      path: '/api/observability/summary'
      fullPath: '/api/observability/summary'
      preLoaderRoute: typeof ApiObservabilitySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/refresh': {
      id: '/api/news/refresh'
      path: '/refresh'
      fullPath: '/api/news/refresh'
      preLoaderRoute: typeof ApiNewsRefreshRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/graph/query': {
      id: '/api/graph/query'
      path: '/api/graph/query'
      fullPath: '/api/graph/query'
      preLoaderRoute: typeof ApiGraphQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliverable/generate': {
      id: '/api/deliverable/generate'
      path: '/api/deliverable/generate'
      fullPath: '/api/deliverable/generate'
      preLoaderRoute: typeof ApiDeliverableGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliverable/export': {
      id: '/api/deliverable/export'
      path: '/api/deliverable/export'
      fullPath: '/api/deliverable/export'
      preLoaderRoute: typeof ApiDeliverableExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consulting/assemble': {
      id: '/api/consulting/assemble'
      path: '/api/consulting/assemble'
      fullPath: '/api/consulting/assemble'
      preLoaderRoute: typeof ApiConsultingAssembleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals/orchestrator': {
      id: '/api/approvals/orchestrator'
      path: '/api/approvals/orchestrator'
      fullPath: '/api/approvals/orchestrator'
      preLoaderRoute: typeof ApiApprovalsOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals/backend': {
      id: '/api/approvals/backend'
      path: '/api/approvals/backend'
      fullPath: '/api/approvals/backend'
      preLoaderRoute: typeof ApiApprovalsBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adoption/metrics': {
      id: '/api/adoption/metrics'
      path: '/api/adoption/metrics'
      fullPath: '/api/adoption/metrics'
      preLoaderRoute: typeof ApiAdoptionMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mrp/canvas/resolve': {
      id: '/api/mrp/canvas/resolve'
      path: '/api/mrp/canvas/resolve'
      fullPath: '/api/mrp/canvas/resolve'
      preLoaderRoute: typeof ApiMrpCanvasResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engagements/$id/sources': {
      id: '/api/engagements/$id/sources'
      path: '/$id/sources'
      fullPath: '/api/engagements/$id/sources'
      preLoaderRoute: typeof ApiEngagementsIdSourcesRouteImport
      parentRoute: typeof ApiEngagementsRoute
    }
    '/api/engagements/$id/patterns': {
      id: '/api/engagements/$id/patterns'
      path: '/$id/patterns'
      fullPath: '/api/engagements/$id/patterns'
      preLoaderRoute: typeof ApiEngagementsIdPatternsRouteImport
      parentRoute: typeof ApiEngagementsRoute
    }
    '/api/engagements/$id/deliverable': {
      id: '/api/engagements/$id/deliverable'
      path: '/$id/deliverable'
      fullPath: '/api/engagements/$id/deliverable'
      preLoaderRoute: typeof ApiEngagementsIdDeliverableRouteImport
      parentRoute: typeof ApiEngagementsRoute
    }
  }
}

interface GemsRouteChildren {
  GemsGemIdRoute: typeof GemsGemIdRoute
  GemsIndexRoute: typeof GemsIndexRoute
}

const GemsRouteChildren: GemsRouteChildren = {
  GemsGemIdRoute: GemsGemIdRoute,
  GemsIndexRoute: GemsIndexRoute,
}

const GemsRouteWithChildren = GemsRoute._addFileChildren(GemsRouteChildren)

interface ApiEngagementsRouteChildren {
  ApiEngagementsIdDeliverableRoute: typeof ApiEngagementsIdDeliverableRoute
  ApiEngagementsIdPatternsRoute: typeof ApiEngagementsIdPatternsRoute
  ApiEngagementsIdSourcesRoute: typeof ApiEngagementsIdSourcesRoute
}

const ApiEngagementsRouteChildren: ApiEngagementsRouteChildren = {
  ApiEngagementsIdDeliverableRoute: ApiEngagementsIdDeliverableRoute,
  ApiEngagementsIdPatternsRoute: ApiEngagementsIdPatternsRoute,
  ApiEngagementsIdSourcesRoute: ApiEngagementsIdSourcesRoute,
}

const ApiEngagementsRouteWithChildren = ApiEngagementsRoute._addFileChildren(
  ApiEngagementsRouteChildren,
)

interface ApiNewsRouteChildren {
  ApiNewsRefreshRoute: typeof ApiNewsRefreshRoute
}

const ApiNewsRouteChildren: ApiNewsRouteChildren = {
  ApiNewsRefreshRoute: ApiNewsRefreshRoute,
}

const ApiNewsRouteWithChildren =
  ApiNewsRoute._addFileChildren(ApiNewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptionRoute: AdoptionRoute,
  AuditFactoryRoute: AuditFactoryRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  ConsultingRoute: ConsultingRoute,
  DashboardRoute: DashboardRoute,
  DeliverableRoute: DeliverableRoute,
  EngagementsRoute: EngagementsRoute,
  GemsRoute: GemsRouteWithChildren,
  GraphRoute: GraphRoute,
  HealthRoute: HealthRoute,
  MondayReviewRoute: MondayReviewRoute,
  NewsRoute: NewsRoute,
  ObservabilityRoute: ObservabilityRoute,
  PatternsRoute: PatternsRoute,
  SettingsRoute: SettingsRoute,
  StorylineRoute: StorylineRoute,
  ApiAudioOverviewRoute: ApiAudioOverviewRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCostRoute: ApiCostRoute,
  ApiDeepResearchRoute: ApiDeepResearchRoute,
  ApiEngagementsRoute: ApiEngagementsRouteWithChildren,
  ApiIngestRoute: ApiIngestRoute,
  ApiMondayReviewRoute: ApiMondayReviewRoute,
  ApiNewsRoute: ApiNewsRouteWithChildren,
  ApiPatternsRoute: ApiPatternsRoute,
  ApiReleaseRoute: ApiReleaseRoute,
  ApiStorylineRoute: ApiStorylineRoute,
  CThreadIdRoute: CThreadIdRoute,
  DebugLogsRoute: DebugLogsRoute,
  VisualGraphRoute: VisualGraphRoute,
  ApiAdoptionMetricsRoute: ApiAdoptionMetricsRoute,
  ApiApprovalsBackendRoute: ApiApprovalsBackendRoute,
  ApiApprovalsOrchestratorRoute: ApiApprovalsOrchestratorRoute,
  ApiConsultingAssembleRoute: ApiConsultingAssembleRoute,
  ApiDeliverableExportRoute: ApiDeliverableExportRoute,
  ApiDeliverableGenerateRoute: ApiDeliverableGenerateRoute,
  ApiGraphQueryRoute: ApiGraphQueryRoute,
  ApiObservabilitySummaryRoute: ApiObservabilitySummaryRoute,
  EmbedCanvasCanvasIdRoute: EmbedCanvasCanvasIdRoute,
  ApiMrpCanvasResolveRoute: ApiMrpCanvasResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
