/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as DeliverableRouteImport } from './routes/deliverable'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdoptionRouteImport } from './routes/adoption'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualGraphRouteImport } from './routes/visual.graph'
import { Route as GemsGemIdRouteImport } from './routes/gems.$gemId'
import { Route as DebugLogsRouteImport } from './routes/debug.logs'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'
import { Route as ApiPatternsRouteImport } from './routes/api/patterns'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as EmbedCanvasCanvasIdRouteImport } from './routes/embed.canvas.$canvasId'
import { Route as ApiObservabilitySummaryRouteImport } from './routes/api/observability.summary'
import { Route as ApiGraphQueryRouteImport } from './routes/api/graph.query'
import { Route as ApiDeliverableGenerateRouteImport } from './routes/api/deliverable.generate'
import { Route as ApiApprovalsOrchestratorRouteImport } from './routes/api/approvals.orchestrator'
import { Route as ApiApprovalsBackendRouteImport } from './routes/api/approvals.backend'
import { Route as ApiAdoptionMetricsRouteImport } from './routes/api/adoption.metrics'
import { Route as ApiMrpCanvasResolveRouteImport } from './routes/api/mrp.canvas.resolve'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverableRoute = DeliverableRouteImport.update({
  id: '/deliverable',
  path: '/deliverable',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionRoute = AdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualGraphRoute = VisualGraphRouteImport.update({
  id: '/visual/graph',
  path: '/visual/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsGemIdRoute = GemsGemIdRouteImport.update({
  id: '/$gemId',
  path: '/$gemId',
  getParentRoute: () => GemsRoute,
} as any)
const DebugLogsRoute = DebugLogsRouteImport.update({
  id: '/debug/logs',
  path: '/debug/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatternsRoute = ApiPatternsRouteImport.update({
  id: '/api/patterns',
  path: '/api/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCanvasCanvasIdRoute = EmbedCanvasCanvasIdRouteImport.update({
  id: '/embed/canvas/$canvasId',
  path: '/embed/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilitySummaryRoute = ApiObservabilitySummaryRouteImport.update({
  id: '/api/observability/summary',
  path: '/api/observability/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphQueryRoute = ApiGraphQueryRouteImport.update({
  id: '/api/graph/query',
  path: '/api/graph/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliverableGenerateRoute = ApiDeliverableGenerateRouteImport.update({
  id: '/api/deliverable/generate',
  path: '/api/deliverable/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApprovalsOrchestratorRoute =
  ApiApprovalsOrchestratorRouteImport.update({
    id: '/api/approvals/orchestrator',
    path: '/api/approvals/orchestrator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApprovalsBackendRoute = ApiApprovalsBackendRouteImport.update({
  id: '/api/approvals/backend',
  path: '/api/approvals/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdoptionMetricsRoute = ApiAdoptionMetricsRouteImport.update({
  id: '/api/adoption/metrics',
  path: '/api/adoption/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMrpCanvasResolveRoute = ApiMrpCanvasResolveRouteImport.update({
  id: '/api/mrp/canvas/resolve',
  path: '/api/mrp/canvas/resolve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/dashboard': typeof DashboardRoute
  '/deliverable': typeof DeliverableRoute
  '/gems': typeof GemsRouteWithChildren
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/observability': typeof ObservabilityRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/patterns': typeof ApiPatternsRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/api/adoption/metrics': typeof ApiAdoptionMetricsRoute
  '/api/approvals/backend': typeof ApiApprovalsBackendRoute
  '/api/approvals/orchestrator': typeof ApiApprovalsOrchestratorRoute
  '/api/deliverable/generate': typeof ApiDeliverableGenerateRoute
  '/api/graph/query': typeof ApiGraphQueryRoute
  '/api/observability/summary': typeof ApiObservabilitySummaryRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/dashboard': typeof DashboardRoute
  '/deliverable': typeof DeliverableRoute
  '/gems': typeof GemsRouteWithChildren
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/observability': typeof ObservabilityRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/patterns': typeof ApiPatternsRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/api/adoption/metrics': typeof ApiAdoptionMetricsRoute
  '/api/approvals/backend': typeof ApiApprovalsBackendRoute
  '/api/approvals/orchestrator': typeof ApiApprovalsOrchestratorRoute
  '/api/deliverable/generate': typeof ApiDeliverableGenerateRoute
  '/api/graph/query': typeof ApiGraphQueryRoute
  '/api/observability/summary': typeof ApiObservabilitySummaryRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/dashboard': typeof DashboardRoute
  '/deliverable': typeof DeliverableRoute
  '/gems': typeof GemsRouteWithChildren
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/observability': typeof ObservabilityRoute
  '/patterns': typeof PatternsRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/patterns': typeof ApiPatternsRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/api/adoption/metrics': typeof ApiAdoptionMetricsRoute
  '/api/approvals/backend': typeof ApiApprovalsBackendRoute
  '/api/approvals/orchestrator': typeof ApiApprovalsOrchestratorRoute
  '/api/deliverable/generate': typeof ApiDeliverableGenerateRoute
  '/api/graph/query': typeof ApiGraphQueryRoute
  '/api/observability/summary': typeof ApiObservabilitySummaryRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adoption'
    | '/dashboard'
    | '/deliverable'
    | '/gems'
    | '/graph'
    | '/health'
    | '/observability'
    | '/patterns'
    | '/settings'
    | '/api/chat'
    | '/api/patterns'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/api/adoption/metrics'
    | '/api/approvals/backend'
    | '/api/approvals/orchestrator'
    | '/api/deliverable/generate'
    | '/api/graph/query'
    | '/api/observability/summary'
    | '/embed/canvas/$canvasId'
    | '/api/mrp/canvas/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adoption'
    | '/dashboard'
    | '/deliverable'
    | '/gems'
    | '/graph'
    | '/health'
    | '/observability'
    | '/patterns'
    | '/settings'
    | '/api/chat'
    | '/api/patterns'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/api/adoption/metrics'
    | '/api/approvals/backend'
    | '/api/approvals/orchestrator'
    | '/api/deliverable/generate'
    | '/api/graph/query'
    | '/api/observability/summary'
    | '/embed/canvas/$canvasId'
    | '/api/mrp/canvas/resolve'
  id:
    | '__root__'
    | '/'
    | '/adoption'
    | '/dashboard'
    | '/deliverable'
    | '/gems'
    | '/graph'
    | '/health'
    | '/observability'
    | '/patterns'
    | '/settings'
    | '/api/chat'
    | '/api/patterns'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/api/adoption/metrics'
    | '/api/approvals/backend'
    | '/api/approvals/orchestrator'
    | '/api/deliverable/generate'
    | '/api/graph/query'
    | '/api/observability/summary'
    | '/embed/canvas/$canvasId'
    | '/api/mrp/canvas/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptionRoute: typeof AdoptionRoute
  DashboardRoute: typeof DashboardRoute
  DeliverableRoute: typeof DeliverableRoute
  GemsRoute: typeof GemsRouteWithChildren
  GraphRoute: typeof GraphRoute
  HealthRoute: typeof HealthRoute
  ObservabilityRoute: typeof ObservabilityRoute
  PatternsRoute: typeof PatternsRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPatternsRoute: typeof ApiPatternsRoute
  CThreadIdRoute: typeof CThreadIdRoute
  DebugLogsRoute: typeof DebugLogsRoute
  VisualGraphRoute: typeof VisualGraphRoute
  ApiAdoptionMetricsRoute: typeof ApiAdoptionMetricsRoute
  ApiApprovalsBackendRoute: typeof ApiApprovalsBackendRoute
  ApiApprovalsOrchestratorRoute: typeof ApiApprovalsOrchestratorRoute
  ApiDeliverableGenerateRoute: typeof ApiDeliverableGenerateRoute
  ApiGraphQueryRoute: typeof ApiGraphQueryRoute
  ApiObservabilitySummaryRoute: typeof ApiObservabilitySummaryRoute
  EmbedCanvasCanvasIdRoute: typeof EmbedCanvasCanvasIdRoute
  ApiMrpCanvasResolveRoute: typeof ApiMrpCanvasResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverable': {
      id: '/deliverable'
      path: '/deliverable'
      fullPath: '/deliverable'
      preLoaderRoute: typeof DeliverableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/graph': {
      id: '/visual/graph'
      path: '/visual/graph'
      fullPath: '/visual/graph'
      preLoaderRoute: typeof VisualGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/$gemId': {
      id: '/gems/$gemId'
      path: '/$gemId'
      fullPath: '/gems/$gemId'
      preLoaderRoute: typeof GemsGemIdRouteImport
      parentRoute: typeof GemsRoute
    }
    '/debug/logs': {
      id: '/debug/logs'
      path: '/debug/logs'
      fullPath: '/debug/logs'
      preLoaderRoute: typeof DebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns': {
      id: '/api/patterns'
      path: '/api/patterns'
      fullPath: '/api/patterns'
      preLoaderRoute: typeof ApiPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/canvas/$canvasId': {
      id: '/embed/canvas/$canvasId'
      path: '/embed/canvas/$canvasId'
      fullPath: '/embed/canvas/$canvasId'
      preLoaderRoute: typeof EmbedCanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/summary': {
      id: '/api/observability/summary'
      path: '/api/observability/summary'
      fullPath: '/api/observability/summary'
      preLoaderRoute: typeof ApiObservabilitySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/query': {
      id: '/api/graph/query'
      path: '/api/graph/query'
      fullPath: '/api/graph/query'
      preLoaderRoute: typeof ApiGraphQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliverable/generate': {
      id: '/api/deliverable/generate'
      path: '/api/deliverable/generate'
      fullPath: '/api/deliverable/generate'
      preLoaderRoute: typeof ApiDeliverableGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals/orchestrator': {
      id: '/api/approvals/orchestrator'
      path: '/api/approvals/orchestrator'
      fullPath: '/api/approvals/orchestrator'
      preLoaderRoute: typeof ApiApprovalsOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approvals/backend': {
      id: '/api/approvals/backend'
      path: '/api/approvals/backend'
      fullPath: '/api/approvals/backend'
      preLoaderRoute: typeof ApiApprovalsBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adoption/metrics': {
      id: '/api/adoption/metrics'
      path: '/api/adoption/metrics'
      fullPath: '/api/adoption/metrics'
      preLoaderRoute: typeof ApiAdoptionMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mrp/canvas/resolve': {
      id: '/api/mrp/canvas/resolve'
      path: '/api/mrp/canvas/resolve'
      fullPath: '/api/mrp/canvas/resolve'
      preLoaderRoute: typeof ApiMrpCanvasResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GemsRouteChildren {
  GemsGemIdRoute: typeof GemsGemIdRoute
}

const GemsRouteChildren: GemsRouteChildren = {
  GemsGemIdRoute: GemsGemIdRoute,
}

const GemsRouteWithChildren = GemsRoute._addFileChildren(GemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptionRoute: AdoptionRoute,
  DashboardRoute: DashboardRoute,
  DeliverableRoute: DeliverableRoute,
  GemsRoute: GemsRouteWithChildren,
  GraphRoute: GraphRoute,
  HealthRoute: HealthRoute,
  ObservabilityRoute: ObservabilityRoute,
  PatternsRoute: PatternsRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPatternsRoute: ApiPatternsRoute,
  CThreadIdRoute: CThreadIdRoute,
  DebugLogsRoute: DebugLogsRoute,
  VisualGraphRoute: VisualGraphRoute,
  ApiAdoptionMetricsRoute: ApiAdoptionMetricsRoute,
  ApiApprovalsBackendRoute: ApiApprovalsBackendRoute,
  ApiApprovalsOrchestratorRoute: ApiApprovalsOrchestratorRoute,
  ApiDeliverableGenerateRoute: ApiDeliverableGenerateRoute,
  ApiGraphQueryRoute: ApiGraphQueryRoute,
  ApiObservabilitySummaryRoute: ApiObservabilitySummaryRoute,
  EmbedCanvasCanvasIdRoute: EmbedCanvasCanvasIdRoute,
  ApiMrpCanvasResolveRoute: ApiMrpCanvasResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
