/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualGraphRouteImport } from './routes/visual.graph'
import { Route as GemsGemIdRouteImport } from './routes/gems.$gemId'
import { Route as DebugLogsRouteImport } from './routes/debug.logs'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as EmbedCanvasCanvasIdRouteImport } from './routes/embed.canvas.$canvasId'
import { Route as ApiMrpCanvasResolveRouteImport } from './routes/api/mrp.canvas.resolve'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualGraphRoute = VisualGraphRouteImport.update({
  id: '/visual/graph',
  path: '/visual/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsGemIdRoute = GemsGemIdRouteImport.update({
  id: '/$gemId',
  path: '/$gemId',
  getParentRoute: () => GemsRoute,
} as any)
const DebugLogsRoute = DebugLogsRouteImport.update({
  id: '/debug/logs',
  path: '/debug/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCanvasCanvasIdRoute = EmbedCanvasCanvasIdRouteImport.update({
  id: '/embed/canvas/$canvasId',
  path: '/embed/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMrpCanvasResolveRoute = ApiMrpCanvasResolveRouteImport.update({
  id: '/api/mrp/canvas/resolve',
  path: '/api/mrp/canvas/resolve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gems': typeof GemsRouteWithChildren
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gems': typeof GemsRouteWithChildren
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gems': typeof GemsRouteWithChildren
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/gems/$gemId': typeof GemsGemIdRoute
  '/visual/graph': typeof VisualGraphRoute
  '/embed/canvas/$canvasId': typeof EmbedCanvasCanvasIdRoute
  '/api/mrp/canvas/resolve': typeof ApiMrpCanvasResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gems'
    | '/health'
    | '/settings'
    | '/api/chat'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/embed/canvas/$canvasId'
    | '/api/mrp/canvas/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gems'
    | '/health'
    | '/settings'
    | '/api/chat'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/embed/canvas/$canvasId'
    | '/api/mrp/canvas/resolve'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gems'
    | '/health'
    | '/settings'
    | '/api/chat'
    | '/c/$threadId'
    | '/debug/logs'
    | '/gems/$gemId'
    | '/visual/graph'
    | '/embed/canvas/$canvasId'
    | '/api/mrp/canvas/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GemsRoute: typeof GemsRouteWithChildren
  HealthRoute: typeof HealthRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  CThreadIdRoute: typeof CThreadIdRoute
  DebugLogsRoute: typeof DebugLogsRoute
  VisualGraphRoute: typeof VisualGraphRoute
  EmbedCanvasCanvasIdRoute: typeof EmbedCanvasCanvasIdRoute
  ApiMrpCanvasResolveRoute: typeof ApiMrpCanvasResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/graph': {
      id: '/visual/graph'
      path: '/visual/graph'
      fullPath: '/visual/graph'
      preLoaderRoute: typeof VisualGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/$gemId': {
      id: '/gems/$gemId'
      path: '/$gemId'
      fullPath: '/gems/$gemId'
      preLoaderRoute: typeof GemsGemIdRouteImport
      parentRoute: typeof GemsRoute
    }
    '/debug/logs': {
      id: '/debug/logs'
      path: '/debug/logs'
      fullPath: '/debug/logs'
      preLoaderRoute: typeof DebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/canvas/$canvasId': {
      id: '/embed/canvas/$canvasId'
      path: '/embed/canvas/$canvasId'
      fullPath: '/embed/canvas/$canvasId'
      preLoaderRoute: typeof EmbedCanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mrp/canvas/resolve': {
      id: '/api/mrp/canvas/resolve'
      path: '/api/mrp/canvas/resolve'
      fullPath: '/api/mrp/canvas/resolve'
      preLoaderRoute: typeof ApiMrpCanvasResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GemsRouteChildren {
  GemsGemIdRoute: typeof GemsGemIdRoute
}

const GemsRouteChildren: GemsRouteChildren = {
  GemsGemIdRoute: GemsGemIdRoute,
}

const GemsRouteWithChildren = GemsRoute._addFileChildren(GemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GemsRoute: GemsRouteWithChildren,
  HealthRoute: HealthRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  CThreadIdRoute: CThreadIdRoute,
  DebugLogsRoute: DebugLogsRoute,
  VisualGraphRoute: VisualGraphRoute,
  EmbedCanvasCanvasIdRoute: EmbedCanvasCanvasIdRoute,
  ApiMrpCanvasResolveRoute: ApiMrpCanvasResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
